<a href="https://colab.research.google.com/github/rupam0708/The_Burnout_Equation/blob/main/The_Burnout_Equation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas numpy matplotlib seaborn scipy statsmodels

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (1.16.3)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

df = pd.read_csv("Mental Health Dataset.csv")

df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292364 entries, 0 to 292363
Data columns (total 17 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Timestamp                292364 non-null  object
 1   Gender                   292364 non-null  object
 2   Country                  292364 non-null  object
 3   Occupation               292364 non-null  object
 4   self_employed            287162 non-null  object
 5   family_history           292364 non-null  object
 6   treatment                292364 non-null  object
 7   Days_Indoors             292364 non-null  object
 8   Growing_Stress           292364 non-null  object
 9   Changes_Habits           292364 non-null  object
 10  Mental_Health_History    292364 non-null  object
 11  Mood_Swings              292364 non-null  object
 12  Coping_Struggles         292364 non-null  object
 13  Work_Interest            292364 non-null  object
 14  Social_Weakness          292364 non-null  object
 15  mental_health_interview  292364 non-null  object
 16  care_options             292364 non-null  object
dtypes: object(17)
memory usage: 37.9+ MB

In [ ]:
df.columns = df.columns.str.strip().str.lower()

In [ ]:
df['mental_health'] = df['treatment'].str.lower().map({'yes':1, 'no':0})

In [ ]:
df[df['mental_health'] == 0].head()

,timestamp,gender,country,occupation,self_employed,family_history,treatment,days_indoors,growing_stress,changes_habits,mental_health_history,mood_swings,coping_struggles,work_interest,social_weakness,mental_health_interview,care_options,mental_health
7,8/27/2014 11:52,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No,0
8,8/27/2014 12:18,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure,0
9,8/27/2014 12:37,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No,0
10,8/27/2014 12:39,Female,United States,Corporate,No,Yes,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure,0
11,8/27/2014 12:40,Female,United States,Corporate,No,No,No,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure,0

In [ ]:
cols = [
    'growing_stress',
    'changes_habits',
    'mental_health_history',
    'mood_swings',
    'coping_struggles',
    'work_interest',
    'social_weakness'
]

for col in cols:
    df[col] = df[col].str.strip().str.lower()
    df[col] = df[col].map({'yes':1, 'no':0})

In [ ]:
df.drop(['timestamp'], axis=1, inplace=True)

In [ ]:
df['mental_health'].mean()

np.float64(0.5048706407081583)

In [ ]:
df.groupby('growing_stress')['mental_health'].mean()
df.groupby('coping_struggles')['mental_health'].mean()
df.groupby('mood_swings')['mental_health'].mean()

Series([], Name: mental_health, dtype: float64)

In [ ]:
df[df['growing_stress']==1]['mental_health'].mean()

np.float64(0.511896280091919)

In [ ]:
df[df['coping_struggles']==1]['mental_health'].mean()

np.float64(0.5101495262105538)

In [ ]:
df[df['mood_swings']==1]['mental_health'].mean()

nan

In [ ]:
df[df['social_weakness']==1]['mental_health'].mean()

np.float64(0.5051797351730762)

In [ ]:
from scipy import stats

In [ ]:
def run_ttest(feature):
    group1 = df[df[feature] == 1]['mental_health']
    group2 = df[df[feature] == 0]['mental_health']

    t_stat, p_value = stats.ttest_ind(group1, group2, equal_var=False)

    print(f"{feature}:")
    print("T-stat =", t_stat)
    print("P-value =", p_value)

    if p_value < 0.05:
        print("Result: Significant\n")
    else:
        print("Result: Not Significant\n")

In [ ]:
features = [
    'growing_stress',
    'coping_struggles',
    'mental_health_history',
    'social_weakness',
    'changes_habits'
]

for f in features:
    run_ttest(f)

growing_stress:
T-stat = 3.9575896277874136
P-value = 7.573718199379644e-05
Result: Significant

coping_struggles:
T-stat = 5.399502604369861
P-value = 6.687843345939336e-08
Result: Significant

mental_health_history:
T-stat = 0.6910140891415574
P-value = 0.4895575116236408
Result: Not Significant

social_weakness:
T-stat = -0.4225544189546601
P-value = 0.6726208711588102
Result: Not Significant

changes_habits:
T-stat = -1.1975493275702644
P-value = 0.23109402416184188
Result: Not Significant

In [ ]:
impact = {}

for col in features:
    impact[col] = df.groupby(col)['mental_health'].mean()[1]

sorted(impact.items(), key=lambda x: x[1], reverse=True)

[('growing_stress', np.float64(0.511896280091919)),
 ('coping_struggles', np.float64(0.5101495262105538)),
 ('social_weakness', np.float64(0.5051797351730762)),
 ('changes_habits', np.float64(0.503702418670051)),
 ('mental_health_history', np.float64(0.5033667498494105))]

In [ ]:
df['growing_stress_cat'] = df['growing_stress'].map({1:'Yes', 0:'No'})
df['coping_struggles_cat'] = df['coping_struggles'].map({1:'Yes', 0:'No'})
df['mood_swings_cat'] = df['mood_swings'].map({1:'Yes', 0:'No'})
df['social_weakness_cat'] = df['social_weakness'].map({1:'Yes', 0:'No'})

In [ ]:
df.to_csv("cleaned_data.csv", index=False)